/**
 * Generated Type Declarations
 * 
 * This file is auto-generated by sports-storage/schema/tables/generate-types.ts
 * Do not edit manually. Regenerate with: npm run generate-types
 * 
 * Generated at: 2025-11-14T00:20:28.161Z
 */

// ============================================================================
// Sports And Formats
// ============================================================================

/**
 * Sport - Select type for sports table
 */
export type Sport = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
};

/**
 * SportInsert - Insert type for sports table
 */
export type SportInsert = {
  id: string;
  lat: number;
  lng: number;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
};

/**
 * ScoreFormat - Select type for scoreFormats table
 */
export type ScoreFormat = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  sportId: string | null;
  scoringMethodName: string;
};

/**
 * ScoreFormatInsert - Insert type for scoreFormats table
 */
export type ScoreFormatInsert = {
  id: string;
  lat: number;
  lng: number;
  scoringMethodName: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  sportId?: string | null | undefined;
};

/**
 * EventFormat - Select type for eventFormats table
 */
export type EventFormat = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  sportId: string;
  scoreFormatId: string;
  minTeamSize: number | null;
  maxTeamSize: number | null;
  minTeams: number | null;
  maxTeams: number | null;
  expectedMinDuration: number | null;
  expectedDuration: number | null;
  expectedMaxDuration: number | null;
};

/**
 * EventFormatInsert - Insert type for eventFormats table
 */
export type EventFormatInsert = {
  id: string;
  lat: number;
  lng: number;
  sportId: string;
  scoreFormatId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  minTeamSize?: number | null | undefined;
  maxTeamSize?: number | null | undefined;
  minTeams?: number | null | undefined;
  maxTeams?: number | null | undefined;
  expectedMinDuration?: number | null | undefined;
  expectedDuration?: number | null | undefined;
  expectedMaxDuration?: number | null | undefined;
};

/**
 * EventFormatStage - Select type for eventFormatStages table
 */
export type EventFormatStage = {
  number: number;
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  scoreFormatId: string;
  eventFormatId: string;
  parentId: string | null;
};

/**
 * EventFormatStageInsert - Insert type for eventFormatStages table
 */
export type EventFormatStageInsert = {
  id: string;
  lat: number;
  lng: number;
  scoreFormatId: string;
  eventFormatId: string;
  number?: number | undefined;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  parentId?: string | null | undefined;
};

/**
 * Score - Select type for scores table
 */
export type Score = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  scoreFormatId: string;
  value: any;
  points: number | null;
  won: boolean | null;
  lost: boolean | null;
  tied: boolean | null;
  winMargin: number | null;
  lossMargin: number | null;
  pointsBehindPrevious: number | null;
  pointsAheadOfNext: number | null;
};

/**
 * ScoreInsert - Insert type for scores table
 */
export type ScoreInsert = {
  id: string;
  lat: number;
  lng: number;
  scoreFormatId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  value?: any;
  points?: number | null | undefined;
  won?: boolean | null | undefined;
  lost?: boolean | null | undefined;
  tied?: boolean | null | undefined;
  winMargin?: number | null | undefined;
  lossMargin?: number | null | undefined;
  pointsBehindPrevious?: number | null | undefined;
  pointsAheadOfNext?: number | null | undefined;
};


// ============================================================================
// Venues
// ============================================================================

/**
 * Venue - Select type for venues table
 */
export type Venue = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
};

/**
 * VenueInsert - Insert type for venues table
 */
export type VenueInsert = {
  id: string;
  lat: number;
  lng: number;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
};

/**
 * VenueEventFormat - Select type for venueEventFormats table
 */
export type VenueEventFormat = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  minTeamSize: number | null;
  maxTeamSize: number | null;
  minTeams: number | null;
  maxTeams: number | null;
  expectedMinDuration: number | null;
  expectedDuration: number | null;
  expectedMaxDuration: number | null;
  eventFormatId: string;
  venueId: string | null;
};

/**
 * VenueEventFormatInsert - Insert type for venueEventFormats table
 */
export type VenueEventFormatInsert = {
  id: string;
  lat: number;
  lng: number;
  eventFormatId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  minTeamSize?: number | null | undefined;
  maxTeamSize?: number | null | undefined;
  minTeams?: number | null | undefined;
  maxTeams?: number | null | undefined;
  expectedMinDuration?: number | null | undefined;
  expectedDuration?: number | null | undefined;
  expectedMaxDuration?: number | null | undefined;
  venueId?: string | null | undefined;
};

/**
 * VenueEventFormatStage - Select type for venueEventFormatStages table
 */
export type VenueEventFormatStage = {
  number: number;
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  parentId: string | null;
  venueEventFormatId: string;
  eventFormatStageId: string;
};

/**
 * VenueEventFormatStageInsert - Insert type for venueEventFormatStages table
 */
export type VenueEventFormatStageInsert = {
  id: string;
  lat: number;
  lng: number;
  venueEventFormatId: string;
  eventFormatStageId: string;
  number?: number | undefined;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  parentId?: string | null | undefined;
};


// ============================================================================
// Participants
// ============================================================================

/**
 * Participant - Select type for participants table
 */
export type Participant = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  sex: Sex;
  birthday: Date | null;
  createdAt: Date | null;
  deletedAt: Date | null;
  isTeam: boolean | null;
};

/**
 * ParticipantInsert - Insert type for participants table
 */
export type ParticipantInsert = {
  id: string;
  lat: number;
  lng: number;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  sex?: Sex | undefined;
  birthday?: Date | null | undefined;
  createdAt?: Date | null | undefined;
  deletedAt?: Date | null | undefined;
  isTeam?: boolean | null | undefined;
};

/**
 * TeamMember - Select type for teamMembers table
 */
export type TeamMember = {
  id: string;
  teamId: string;
  participantId: string;
};

/**
 * TeamMemberInsert - Insert type for teamMembers table
 */
export type TeamMemberInsert = {
  id: string;
  teamId: string;
  participantId: string;
};


// ============================================================================
// Events
// ============================================================================

/**
 * Event - Select type for events table
 */
export type Event = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  venueEventFormatId: string;
  startTime: Date | null;
  endTime: Date | null;
  active: boolean | null;
};

/**
 * EventInsert - Insert type for events table
 */
export type EventInsert = {
  id: string;
  lat: number;
  lng: number;
  venueEventFormatId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  startTime?: Date | null | undefined;
  endTime?: Date | null | undefined;
  active?: boolean | null | undefined;
};

/**
 * EventParticipant - Select type for eventParticipants table
 */
export type EventParticipant = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  participantId: string;
  eventId: string;
};

/**
 * EventParticipantInsert - Insert type for eventParticipants table
 */
export type EventParticipantInsert = {
  id: string;
  lat: number;
  lng: number;
  participantId: string;
  eventId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
};

/**
 * EventStage - Select type for eventStages table
 */
export type EventStage = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  startTime: Date | null;
  endTime: Date | null;
  active: boolean | null;
  eventId: string;
  venueEventFormatStageId: string;
};

/**
 * EventStageInsert - Insert type for eventStages table
 */
export type EventStageInsert = {
  id: string;
  lat: number;
  lng: number;
  eventId: string;
  venueEventFormatStageId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  startTime?: Date | null | undefined;
  endTime?: Date | null | undefined;
  active?: boolean | null | undefined;
};

/**
 * ParticipantEventStageScore - Select type for participantEventStageScores table
 */
export type ParticipantEventStageScore = {
  id: string;
  name: string | null;
  notes: string | null;
  lat: number;
  lng: number;
  metadata: Record<string, any> | null;
  scoreFormatId: string;
  value: any;
  points: number | null;
  won: boolean | null;
  lost: boolean | null;
  tied: boolean | null;
  winMargin: number | null;
  lossMargin: number | null;
  pointsBehindPrevious: number | null;
  pointsAheadOfNext: number | null;
  participantId: string;
  eventStageId: string | null;
  completedAt: Date | null;
  complete: boolean;
};

/**
 * ParticipantEventStageScoreInsert - Insert type for participantEventStageScores table
 */
export type ParticipantEventStageScoreInsert = {
  id: string;
  lat: number;
  lng: number;
  scoreFormatId: string;
  participantId: string;
  name?: string | null | undefined;
  notes?: string | null | undefined;
  metadata?: Record<string, any> | null | undefined;
  value?: any;
  points?: number | null | undefined;
  won?: boolean | null | undefined;
  lost?: boolean | null | undefined;
  tied?: boolean | null | undefined;
  winMargin?: number | null | undefined;
  lossMargin?: number | null | undefined;
  pointsBehindPrevious?: number | null | undefined;
  pointsAheadOfNext?: number | null | undefined;
  eventStageId?: string | null | undefined;
  completedAt?: Date | null | undefined;
  complete?: boolean | undefined;
};


// ============================================================================
// Photos
// ============================================================================

/**
 * Photo - Select type for photos table
 */
export type Photo = {
  id: string;
  data: string | null;
  createdAt: number;
  refId: string | null;
  refTable: string | null;
  hash: string;
};

/**
 * PhotoInsert - Insert type for photos table
 */
export type PhotoInsert = {
  id: string;
  hash: string;
  data?: string | null | undefined;
  createdAt?: number | undefined;
  refId?: string | null | undefined;
  refTable?: string | null | undefined;
};


// ============================================================================
// Accounts
// ============================================================================

/**
 * Account - Select type for accounts table
 */
export type Account = {
  id: string;
  deletedAt: Date | null;
  participantId: string | null;
};

/**
 * AccountInsert - Insert type for accounts table
 */
export type AccountInsert = {
  id: string;
  deletedAt?: Date | null | undefined;
  participantId?: string | null | undefined;
};


// ============================================================================
// Settings
// ============================================================================

/**
 * SettingOption - Select type for settingOptions table
 */
export type SettingOption = {
  id: string;
  name: string | null;
  spec: unknown;
};

/**
 * SettingOptionInsert - Insert type for settingOptions table
 */
export type SettingOptionInsert = {
  id: string;
  name?: string | null | undefined;
  spec?: unknown;
};

/**
 * AccountSettingOption - Select type for accountSettingOptions table
 */
export type AccountSettingOption = {
  value: unknown;
  accountId: string | null;
  settingOptionId: string | null;
  updatedAt: Date | null;
};

/**
 * AccountSettingOptionInsert - Insert type for accountSettingOptions table
 */
export type AccountSettingOptionInsert = {
  value?: unknown;
  accountId?: string | null | undefined;
  settingOptionId?: string | null | undefined;
  updatedAt?: Date | null | undefined;
};


// ============================================================================
// Data Merges
// ============================================================================

/**
 * MergeEntry - Select type for mergeEntries table
 */
export type MergeEntry = {
  id: string;
  refTable: string;
  foreignStorageId: string;
  foreignId: string;
  localId: string;
  mergedAt: number;
};

/**
 * MergeEntryInsert - Insert type for mergeEntries table
 */
export type MergeEntryInsert = {
  id: string;
  refTable: string;
  foreignStorageId: string;
  foreignId: string;
  localId: string;
  mergedAt: number;
};


