/**
 * Migration Files Index
 * 
 * This file is auto-generated by generate-migrations-index.ts
 * Do not edit manually. Run `npm run db:generate` to regenerate.
 * 
 * Contains all migration SQL files that will be executed at runtime.
 */

// This will be populated automatically by the generation script
export default [] as Array<{ name: string; hash: string; sql: string }>;

