/**
 * Migration Files Index
 * 
 * This file is auto-generated by generate-migrations.ts
 * Do not edit manually.
 * 
 * Contains all migration SQL files that will be executed at runtime.
 */

export default [] as Array<{ name: string; hash: string; sql: string }>;
