/**
 * Generate All Migrations
 * 
 * Generates migration files for all modules.
 * Migrations are used to upgrade existing databases when schema changes.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

const PROJECT_ROOT = path.join(__dirname, '../');

interface Migration {
  name: string;
  hash: string;
  sql: string;
}

interface ModuleConfig {
  name: string;
  configPath: string;
  migrationsDir: string;
  indexFile: string;
}

const modules: ModuleConfig[] = [
  {
    name: 'generic-sports-data',
    configPath: path.resolve(__dirname, 'generic-sports-data/drizzle.config.ts'),
    migrationsDir: path.join(__dirname, 'generic-sports-data/migrations'),
    indexFile: path.join(__dirname, 'generic-sports-data/migrations/index.ts'),
  },
  {
    name: 'accounts',
    configPath: path.resolve(__dirname, 'accounts/drizzle.config.ts'),
    migrationsDir: path.join(__dirname, 'accounts/migrations'),
    indexFile: path.join(__dirname, 'accounts/migrations/index.ts'),
  },
];

/**
 * Convert backticks to double quotes in SQL (SQLite standard)
 */
function convertToSQLite(sql: string): string {
  return sql.replace(/`/g, '"');
}

/**
 * Generate hash from SQL content
 */
function hashSQL(sql: string): string {
  return crypto.createHash('md5').update(sql).digest('hex').substring(0, 16);
}

/**
 * Generate migrations index for a module
 */
function generateMigrationsIndex(module: ModuleConfig): void {
  if (!fs.existsSync(module.migrationsDir)) {
    console.warn(`⚠️  Migrations directory not found: ${module.migrationsDir}`);
    fs.writeFileSync(module.indexFile, `export default [] as Array<{ name: string; hash: string; sql: string }>;\n`);
    return;
  }
  
  const files = fs.readdirSync(module.migrationsDir)
    .filter(file => file.endsWith('.sql'))
    .sort();
  
  if (files.length === 0) {
    console.warn(`⚠️  No migration files found for ${module.name}.`);
    fs.writeFileSync(module.indexFile, `export default [] as Array<{ name: string; hash: string; sql: string }>;\n`);
    return;
  }
  
  const migrations: Migration[] = [];
  
  for (const file of files) {
    const filePath = path.join(module.migrationsDir, file);
    let sql = fs.readFileSync(filePath, 'utf-8');
    sql = convertToSQLite(sql);
    fs.writeFileSync(filePath, sql);
    
    const hash = hashSQL(sql);
    const name = file.replace('.sql', '');
    
    migrations.push({
      name,
      hash,
      sql: sql.trim(),
    });
  }
  
  const migrationObjects: string[] = [];
  
  migrations.forEach((migration) => {
    const escapedSQL = migration.sql
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\${/g, '\\${');
    
    migrationObjects.push(`{
    name: '${migration.name}',
    hash: '${migration.hash}',
    sql: "${escapedSQL}"
  }`);
  });
  
  const content = `/**
 * Migration Files Index
 * 
 * This file is auto-generated by generate-all-migrations.ts
 * Do not edit manually.
 * 
 * Contains all migration SQL files that will be executed at runtime.
 */

export default [
${migrationObjects.map(m => '  ' + m).join(',\n')}
] as Array<{ name: string; hash: string; sql: string }>;
`;
  
  fs.writeFileSync(module.indexFile, content);
  console.log(`✅ Generated migrations index with ${migrations.length} migration(s)`);
}

/**
 * Generate migrations for a module
 */
function generateModuleMigrations(module: ModuleConfig): void {
  console.log(`🔧 Generating ${module.name} migrations...`);
  
  try {
    let exitCode = 0;
    let output = '';
    try {
      output = execSync(`npx drizzle-kit generate --config "${module.configPath}"`, { 
        stdio: ['inherit', 'pipe', 'pipe'],
        cwd: PROJECT_ROOT,
        encoding: 'utf-8'
      }) as string;
    } catch (execError: any) {
      exitCode = execError.status || execError.code || 1;
      output = (execError.stdout || '') + (execError.stderr || '') + (execError.message || '');
      
      if (output.includes('ERR_MODULE_NOT_FOUND') || 
          output.includes('Cannot find module') ||
          output.includes('Error')) {
        console.error('❌ Drizzle-kit encountered errors:');
        console.error(output);
        throw new Error(`Drizzle-kit failed with exit code ${exitCode}. See errors above.`);
      }
      
      if (exitCode !== 0) {
        console.error('❌ Drizzle-kit failed:');
        console.error(output);
        throw execError;
      }
    }
    
    if (!fs.existsSync(module.migrationsDir)) {
      throw new Error('Migrations directory was not created. Drizzle-kit may have failed silently.');
    }
    
    const sqlFiles = fs.readdirSync(module.migrationsDir).filter(f => f.endsWith('.sql'));
    if (sqlFiles.length === 0) {
      console.error('❌ No migration files were generated.');
      if (output) {
        console.error('Drizzle-kit output:', output);
      }
      throw new Error('No migration files were generated. Check drizzle-kit output above for errors.');
    }
    
    generateMigrationsIndex(module);
    console.log(`✅ ${module.name} migrations generated successfully!`);
  } catch (error: any) {
    console.error(`❌ Error generating ${module.name} migrations:`, error);
    if (error.status !== undefined || error.code !== undefined) {
      console.error('   Exit code:', error.status || error.code);
    }
    if (error.stdout) {
      console.error('   stdout:', error.stdout.toString());
    }
    if (error.stderr) {
      console.error('   stderr:', error.stderr.toString());
    }
    throw error;
  }
}

/**
 * Generate all migrations
 */
function generateAll(): void {
  console.log('🚀 Generating all migrations...\n');
  
  try {
    for (const module of modules) {
      generateModuleMigrations(module);
      console.log('');
    }
    
    console.log('🎉 All migrations generated successfully!');
    console.log('   Migrations will be applied automatically on database setup');
  } catch (error: any) {
    console.error('❌ Error generating migrations:', error);
    process.exit(1);
  }
}

generateAll();
