/**
 * CREATE Scripts Index
 * 
 * This file is auto-generated by schema.gen()
 * Do not edit manually. Run the generate script to regenerate.
 */

import * as fs from 'fs';
import * as path from 'path';

const scriptsDir = __dirname;

// Read CREATE scripts
const pgScriptPath = path.join(scriptsDir, 'create-script.pg.sql');
const sqliteScriptPath = path.join(scriptsDir, 'create-script.sqlite.sql');

let pgScript: string | null = null;
let sqliteScript: string | null = null;

try {
  if (fs.existsSync(pgScriptPath)) {
    pgScript = fs.readFileSync(pgScriptPath, 'utf-8');
  }
} catch (error) {
  console.warn('Could not read PostgreSQL CREATE script:', error);
}

try {
  if (fs.existsSync(sqliteScriptPath)) {
    sqliteScript = fs.readFileSync(sqliteScriptPath, 'utf-8');
  }
} catch (error) {
  console.warn('Could not read SQLite CREATE script:', error);
}

export const createScripts = {
  postgres: pgScript ? { sql: pgScript } : null,
  sqlite: sqliteScript ? { sql: sqliteScript } : null,
};
